- name: Fetch build output folder from moc
  hosts: moc
  tasks:
    - synchronize:
        src: "/home/{{ ansible_user }}/{{ network_name }}" 
        dest: "{{ destination | default ('/tmp/' ~ network_name) }}"
        mode: pull
  tags:
    - build
    
- name: Fetch test output files from moc
  hosts: moc
  tasks:
    - synchronize:
        src: "{{ item }}" 
        dest: "{{ destination | default ('/tmp/' ~ network_name) }}"
        mode: pull
      with_items:
        - "/home/{{ ansible_user }}/tests/helper-scripts/network-tests/error.log"
        - "/home/{{ ansible_user }}/tests/helper-scripts/network-tests/combined.log"
  tags:
    - tests
    